name: 'Submit to Web Store'

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: install pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies and build artifact
        run: |
          cd apps/extension
          pnpm install
          pnpm build -- --zip
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v2
        with:
          keys: ${{ secrets.BPP_KEYS }}
          artifact: build/chrome-mv3-prod.zip
